<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-57FQFH3S" ignored="0" name="test1" tests="5" failures="3" timestamp="2020-11-11T10:10:45 CST" time="16.431" errors="0">
  <testcase name="Demo1_success" time="0.012" classname="Test_1.login_test"/>
  <testcase name="Demo2_fail" time="0.003" classname="Test_1.login_test">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
at Test_1.login_test.Demo2_fail(login_test.java:54)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- Demo2_fail -->
  <testcase name="Demo3_fail" time="0.002" classname="Test_1.login_test">
    <failure type="java.lang.AssertionError" message="expected [4] but found [7]">
      <![CDATA[java.lang.AssertionError: expected [4] but found [7]
at Test_1.login_test.Demo3_fail(login_test.java:63)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- Demo3_fail -->
  <testcase name="Demo4_fail" time="0.001" classname="Test_1.login_test">
    <failure type="java.lang.AssertionError" message="expected [9] but found [7]">
      <![CDATA[java.lang.AssertionError: expected [9] but found [7]
at Test_1.login_test.Demo4_fail(login_test.java:70)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- Demo4_fail -->
  <testcase name="loginSuccess" time="7.806" classname="Test_1.login_test"/>
</testsuite> <!-- test1 -->
